### ISSUE TITLE
unable to build for linux?

### ISSUE THREAD

**Issue by pawmart** [hashgraph/hedera-sdk-go#1]
I get this error message when trying to build my app... Any suggestions?

```
# github.com/hashgraph/hedera-sdk-go
vendor/github.com/hashgraph/hedera-sdk-go/libs/x86_64-unknown-linux-gnu/libhedera.a(std-36d4266b7b8bdd72.std.ebiq8be3-cgu.0.rcgu.o):(.text._ZN3std3net4addr19resolve_socket_addr17ha12e3def354be31fE+0x195): undefined reference to `__res_init'
collect2: error: ld returned 1 exit status
```

**Comment by pawmart** [comment]
OK, thank you for your comment.

I am running / trying to build inside docker image 'alpine' distro: "golang:alpine" specifically, with installed git-flfs

```
FROM golang:alpine
ARG SSH_KEY
RUN apk update && apk add --no-cache git curl openssh-client gcc g++ musl-dev
WORKDIR /go/src
RUN wget -qO- https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-linux-amd64-2.1.1.tar.gz | tar xz
RUN mv git-lfs-*/git-lfs /usr/bin/ && rm -rf git-lfs-*
RUN go get -u github.com/golang/dep/cmd/dep
RUN mkdir ~/.ssh
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN git config --global url.git@github.com:.insteadOf https://github.com/
RUN mkdir -p /go/src/app
```

I am running the build like this:

```
APP_NAME=hederablockchain-srv
PACKAGE_NAME=github.com/avoco-identity/hederablockchain-srv
VERSION=latest

	docker run --rm -v ${PWD}:/go/src/${PACKAGE_NAME} -e CGO_ENABLED=1 -e GOOS=linux -e GOARCH=amd64 \
		avoco/go-builder:v6 /bin/sh -c "git lfs install && dep ensure && go build -o app" && \
	docker build -t ${APP_NAME}:${VERSION} .
```

I have updated sdk package locally and in 'dep' and have the same issue ;/

**Comment by mehcode** [comment]
@pawmart Thank you for the detailed information. This should be fixed now. I adjusted how artifacts are produced for linux to make them more portable.

The error we were getting was that we had a dependency on `glibc` so you couldn't use `musl`. I see no reason to keep that dependency so I dropped it and use `musl` to compile the linux artifacts.

**Comment by pawmart** [comment]
Perfect, this is now building fine. I have an issue with processing transaction now but I will raise this as separate issue if no luck...
