### ISSUE TITLE
Account balance re-reading does not return same value

### ISSUE THREAD

**Issue by goldenchain03** [hashgraph/hedera-sdk-go#10]
I have a sample code to read my account balance and other account balance.
The other account balance returned remains zero -- even when I have use my accountID again.

	// Depricated: myAccount := hedera.NewAccountID(0, 0, 1001)
	myAccount := hedera.AccountID{Account: <my 4digit ac id>}

	balance, err := client.GetAccountBalance(myAccount).Answer()
	if err != nil {
		panic(err)
	}

	fmt.Printf("Your balance: %v \n", balance/1000000000)

	time.Sleep(1 * time.Second)

	// Depricated: otherAccount := hedera.NewAccountID(0, 0, 1065)
	otherAccount := hedera.AccountID{Account: <my 4digit ac id>}

	otherBalance, err := client.GetAccountBalance(otherAccount).Answer()
	time.Sleep(1 * time.Second)

	fmt.Printf("Other account balance: %v \n", otherBalance/1000000000)

	time.Sleep(1 * time.Second)

**Comment by mehcode** [comment]
@goldenchain03 My guess is that because you're not handling the `err` when requesting balance again something is going wrong. In Go, if there is an error result then all other values from the return are zero-initialized.

**Comment by goldenchain03** [comment]
I put the err catching code, did not get an error, but the re-reading returned same amount.
