### ISSUE TITLE
observing excessive "transport is closing" errors that slows down test

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#100]
Starting a week ago, I observed a slow down of my test after running just
couple minutes.  After turning on grpc tracing, it shows the following
error in transport layer:

    INFO: 2020/11/18 15:39:13 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

The error itself looks normal, grpc handles it by doing re-tries.  I could see
in good transactions it can take couple re-tries to get the connection
established/stabilized and to complete the transaction. Worst case it sets 
a 20 seconds timeout to quit and let upper layer to decide what to do, in 
this case the sdk would do a re-try and the client(in this my test code) normally
sees a successful transaction returned.

This is a common practice to handle intermittent networking issues, but in
my case after couple minutes there seems to be persistent "transport is closing"
errors that kept the program stuck in the 20 seconds re-try loop every time it tries
a transaction.  A follow up SDK re-try after the first 20 seconds delay would
pass but the test keeps getting the same delay, the performance of the test
went downhill.

The "transport is closing" error could be due to the server side issue, but I
want to report it here to see if there may be other reasons that could cause the
connection to fail.

My test is doing simple transaction call, such as message submit or token transfer,
repeatly in a loop. The test could run in hundreds threads until a week ago and never  
had seen this issue.  And I could reproduce this with just a single thread.

I tried to upgrade to the latest sdk(v2) and rebuilt all supporting modules and
didn't seem to help. 

I am running

    # go version
    go version go1.13.15 linux/amd64

but i also tried 1.15, no difference.

Attached is the log file w/ grpc tracing, "LATENCY" lines are from my test code which tracks the time on the API call,
when it starts to show something like this:

    15:40:39.452 INFO LATENCY = 20087ms

it started the slow down period.  

    15:40:39.366 INFO [SDK][0] ......method_transaction_error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.74.82.254:50211: i/o timeout"

this is the log added in SDK where it would do a re-try.

Let me know if you need more information.  The attached log stopped after just couple long delays.

[log.txt](https://github.com/hashgraph/hedera-sdk-go/files/5568650/log.txt)

**Comment by tomzhenghedera** [comment]
Latest update:

I upgraded my env to latest master branch, which received an upgrade to grpc v1.32.0:

```
# git describe --tag 
v2.1.1-3-gbda3454
```

cleaned up and rebuilt my env, reran the tests.  The program seems to be able to run longer without hitting the 20 s delay.  Though the program started to hit this error:

`15:30:16.726 INFO Error: max retry count has been hit`

I increased MaxRetry counter but it would just prolong the time first hit the error.

I ran two of my tests, each does a simple loop of a single transaction, here are the two types:

- message submit
- token transfer

error should be seen under 3 mins of the test run.

**Comment by danielakhterov** [comment]
I think this is due to the fact we weren't delaying on a grpc status `UNAVAILABLE` or `RESOURCE_EXHAUSTED`. I think this fixed on master, but I'll keep this issue open for now. Our tests no longer produce the transport is closing error, but could you retry your tests with the current version on master.

**Comment by tomzhenghedera** [comment]
Got to this late.   I will try this again in the morning and will report back.

**Comment by danielakhterov** [comment]
@tomzhenghedera I've heard nothing as of yet, so I'm going to assume issue is now resolved. Please re-open if you're still having trouble.
