### ISSUE TITLE
Update TokenCreateTransaction method names v2.1.0

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#102]
Update the following methods for TokenCreateTransaction to match the other v2 SDKs

- [ ] `SetName() -> SetTokenName()`

- [ ] `SetSymbol() -> SetTokenSymbol()`

- [ ] `SetTreasury() -> SetTreasuryAccountId()`

**Comment by SimiHunjan** [comment]
Actually, looks like it is my IDE. If I use `SetName()` it errors, but it doesn't show `SetTokenName()`, `SetTokenSymbol()`, etc. Not sure why it is not showing the right name?
![Screen Shot 2020-11-29 at 2 57 04 PM](https://user-images.githubusercontent.com/21989138/100555907-61d5ad80-3253-11eb-93ae-fad35ab99400.png)

**Comment by danielakhterov** [comment]
I'm not sure on why your IDE is doing that, but currently master has ```Token[Create|Update].[Set|Get]Token[Name|Symbol|TreasuryAccountID]()``` so I'll close this issue. Please reopen if you're still having trouble.
