### ISSUE TITLE
hedera.NewTransferTransaction is marked as deprecated

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#103]
v2.1.0

I am not sure why `hedera.NewTransferTransaction` is marked as deprecated as this is what is used in the other SDKs. 

![Screen Shot 2020-11-29 at 2 30 15 PM](https://user-images.githubusercontent.com/21989138/100555327-86c82180-324f-11eb-8e2a-76aa6e40c8a2.png)

**Comment by danielakhterov** [comment]
This should now be fixed, and will be present in next release.
