### ISSUE TITLE
hedera.PrivateKeyFromStringECDSA in the Go SDK is not functionally equivalent to PrivateKey.fromStringECDSA in the JS SDK

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-sdk-go#1057]
### Description

In the Go SDK, and extra step is required. See the steps to reproduce below.

### Steps to reproduce

In the JS SDK you can do this:
```js
    const operatorKey = PrivateKey.fromStringECDSA(operatorKeyStr);
```

However, in the Go SDK, if you do this, you will get an error:
```go
	operatorKey, _ := hedera.PrivateKeyFromStringECDSA(operatorKeyStr)
```

Turns out that the Go SDK does not handle the `0x` prefix in a hexadecimal format ECDSA secp256k1 private key automatically, and this needs to be done manually:
```go
	operatorKeyStr = strings.TrimPrefix(operatorKeyStr, "0x")
	operatorKey, _ := hedera.PrivateKeyFromStringECDSA(operatorKeyStr)
```

### Additional context

Nil

### Hedera network

testnet

### Version

github.com/hashgraph/hedera-sdk-go/v2 v2.37.0 // indirect

### Operating system

macOS

**Comment by 0xivanov** [comment]
Thanks for pointing that out!
