### ISSUE TITLE
TopicMessageSubmitTransaction.SetMessage in the Go SDK is not functionally equivalent to TopicMessageSubmitTransaction.setMessage in the JS SDK

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-sdk-go#1066]
### Description

In the Go SDK, and extra step is required. See the steps to reproduce below.

### Steps to reproduce

In the JS SDK you can do this:
```js
  const topicMsgSubmitTx = await new TopicMessageSubmitTransaction()
    .setTopicId(topicId)
    .setMessage('Hello HCS!')
    .freezeWith(client);
```

However, in the Go SDK, if you do this, you will get an error:
```go
	topicMsgSubmitTx, _ := hedera.NewTopicMessageSubmitTransaction().
	  SetTopicID(*topicId).
	  SetMessage("Hello HCS!").
	  FreezeWith(client);
```

Turns out that the Go SDK does not accept a string as the parameter, and a typecast to be done manually:
```go
	topicMsgSubmitTx, _ := hedera.NewTopicMessageSubmitTransaction().
	  SetTopicID(*topicId).
	  SetMessage([]byte("Hello HCS!")).
	  FreezeWith(client);
```

### Additional context

nil

### Hedera network

testnet

### Version

github.com/hashgraph/hedera-sdk-go/v2 v2.37.0 // indirect

### Operating system

macOS

**Comment by 0xivanov** [comment]
Hey @bguiz , thanks for opening this issue. It seems like in Go we are missing the method that accepts string as a parameter. Will be added in the next release.
