### ISSUE TITLE
Replace ethereum-go library

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#1109]
### Problem

As the project is moving to the Linux foundation, we need to replace this library. 

- [x] #1111 
- [x] #1112 
- [x] #1113 
- [x] #1114 
- [x] #1115

### Solution

Look for solutions to replace this library.

**Comment by SimiHunjan** [comment]
https://github.com/ethereum/go-ethereum

**Comment by 0xivanov** [comment]
Done with https://github.com/hashgraph/hedera-sdk-go/pull/1124
