### ISSUE TITLE
[Proposal] Network pool

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#113]
Currently I think we maintain active connection with a node as long as next transaction stays on the same node, also there is a retry counter we can set how many times we want to re-try on the node before we try next node.  The management of the connections is hidden from the user I believe.  I can see there may be use case for facilitating and maintaining a pool of active connections with each available node, that way for timing sensitive application, as soon as on the first failure of one transaction on one node, it can switch to next (previously set up)connection on a different node.  This will save the re/new connection time and the delay caused by re-tries.

Of course, this may lead to security concerns such as resource abuse to the server side that has to be considered, but nothing one can't do today.

**Comment by danielakhterov** [comment]
I'm thinking we can do something like `Client.setPoolSize(10)` which would maintain 10 connections per node and cycle between the connections when making requests.

@mehcode You might have some thoughts on this.

**Comment by danielakhterov** [comment]
Closing in favor of https://github.com/hashgraph/hedera-sdk-java/discussions/581
