### ISSUE TITLE
Add tinybar symbol when printing the balance of tinybars

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#115]
Code Sample:

```
	newAccountBalancequery := hedera.NewAccountBalanceQuery().
		SetAccountID(newAccountId)

	newAccountBalance, err := newAccountBalancequery.Execute(client)
	if err != nil {
		panic(err)
	}

	//Print the balance of hbars
	fmt.Println("The hbar account balance for this account is ", newAccountBalance.Hbars.AsTinybar())
```

Console:

`The hbar account balance for this account is 2000`

Should be: 
`The hbar account balance for this account is 2000 tħ
`

**Comment by danielakhterov** [comment]
`Hbar.AsTinybar()` returns an `int64` so you can use the value directly. If you want to print the hbars with the proper suffix please use `Hbar.String()` or `Hbar.ToString(HbarUnit)`. If you'd like to print the value specifically as tinybars I'd recommend  `Hbar.ToString(HbarUnit.Tinybar)`. If you're having further troubles please re-open issue.
