### ISSUE TITLE
Token service comments do not match functions

### ISSUE THREAD

**Issue by sam-at-luther** [hashgraph/hedera-sdk-go#118]
Something seems off with the function descriptions in the token service. For example, in:
https://github.com/hashgraph/hedera-sdk-go/blob/bf614fa67a53f5311d4f52783d72fc42c18a02ee/token_create_transaction.go#L31

You'll see the comment:

```
// Specifies the initial supply of tokens to be put in circulation. The initial supply is sent to the Treasury Account. The supply is in the lowest denomination possible.
func (transaction *TokenCreateTransaction) SetTreasuryAccountID(treasury AccountID) *TokenCreateTransaction {
```

Which looks like a description for the initial supply, not the function to set the treasury account ID.  Some public functions are also not documented. I've found `go lint` helpful in catching these issues.

**Comment by danielakhterov** [comment]
Thank you for the issue. It seems I copied the doc comments from the protobufs in incorrect order. I've fixed this and this should be part of the next release. Thank you @sam-at-luther 

As for `go lint` do you mean https://github.com/golang/lint which _from what I can tell_ is actually `golint`? We'll be sure start using it.

**Comment by sam-at-luther** [comment]
Yep, that was the one I had in mind.
