### ISSUE TITLE
TransactionID protobuf not updated to latest version

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#120]
`TransactionID`  protobuf is not updated to latest version [here](https://github.com/hashgraph/hedera-protobufs/blob/main/services/BasicTypes.proto#L72).

**Comment by danielakhterov** [comment]
Thanks for the issue. Protobufs have now been updated and should be available in the next release. https://github.com/hashgraph/hedera-sdk-go/blob/2cf4c374343a24d7b4583281311699cd4ec649a1/proto/BasicTypes.proto#L74
