### ISSUE TITLE
Update SDK to support HCS message size limit

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-sdk-go#127]
HCS will be updated to have a HCS message size limit of 1024 bytes. Users who attempt to submit larger messages should be easily able to have those messages chunked into multiple successive messages. This is targeted for the May mainnet update.

https://github.com/hashgraph/hedera-services/issues/1145

**Comment by danielakhterov** [comment]
Closing issue as this is fixed in the latest release.
