### ISSUE TITLE
v2 TopicMessageQuery subscription stops receiving new messages

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#130]
Hello,
After some time (e.g. 5mins) the `TopicMessageQuery` subscription stops receiving new messages
```go
_, err := hedera.NewTopicMessageQuery().
		SetStartTime(time.Unix(0, startTime)).
		SetTopicID(topicID).
		Subscribe(
		        nodeClient.GetClient(),
			func(topicMsg hedera.TopicMessage) {
				// process message
			},
		)
```
Current version: `v2.1.4`

`hedera-sdk-go` version `v0.9.2-0.20201119035034-eb12bcfaed24` does not have this problem.

**Comment by danielakhterov** [comment]
Just tested `TopicMessageQuery` for 10 minutes and it seems to be working fine. I modified `examples/consensus_pub_sub/main.go` and I'll push the changes; can you run the example and make sure that works for you.
You can run it using `go run examples/consensus_pub_sub/main.go`

**Comment by failfmi** [comment]
On which network have you tested it?

**Comment by danielakhterov** [comment]
I tested this on `testnet`, but I'll double check with `previewnet` to see if the error occurs after 30 mins, and post my findings here.

**Comment by danielakhterov** [comment]
Ran 45 minutes on `previewnet`
```v2 on  master [!] via 🐹 v1.16.2
❯ go run examples/consensus_pub_sub/main.go
topicID: 0.0.17159
retry 0/10: rpc error: code = Internal desc = server closed the stream without sending trailers : error submitting topic

v2 on  master [!] via 🐹 v1.16.2 took 41m18s
❯ go run examples/consensus_pub_sub/main.go
topicID: 0.0.17205
Received message 47399

v2 on  master [!] via 🐹 v1.16.2 took 45m4s
❯
```

For the first run it seems the server closed connection for transaction submissions not the mirror.
For the second run it seems to have run file for 45m.

One thing I changed was how long to sleep between submissions from 2 seconds to 10 seconds which is why the number of received messages is so much lower than expected, but I don't think that would change the results.

**Comment by failfmi** [comment]
Thank you for testing it. We have decided to not use the `Subscribe` functionality due to its odd behaviour on our side after just upgrading the version. Again, thanks for the fast response.

**Comment by danielakhterov** [comment]
I'm sorry I could not be of more help, but I don't know how to fix something when I don't know what is broken; closing issue for the time being. If you try to use the `Subscribe` functionality again and it continues to produce odd behaviors please re-open this issue, or open another one.
