### ISSUE TITLE
v2.1.5 beta scheduled transactions receipt failing statuses

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#131]
When submitting identical scheduled transaction in the near future (e.g. cryptocreate), the transaction response `GetReceipt` returns an error `exceptional precheck status IDENTICAL_SCHEDULE_ALREADY_CREATED`.
1. `IDENTICAL_SCHEDULE_ALREADY_CREATED` is not a precheck status
2. The receipt request itself should not resolve with an error, but more like with a transaction receipt, which has the status

**Comment by danielakhterov** [comment]
Thanks for pointing this out; I did not know that a `TransactionReceipt` would be populated accordingly with any status besides `SUCCESS`. Also, thanks for reminding me that the Go SDK hasn't had the error handling refactor that both Java and JS have had. I believe I have fixed this this issue now with the v2.1.5-beta.3 I've also added a regression test for this particular status here: https://github.com/hashgraph/hedera-sdk-go/blob/master/schedule_create_transaction_test.go#L337 If you're still having issues with the latest beta release please re-open this issue.
