### ISSUE TITLE
Automatic operator signing issue on transfers including additional senders

### ISSUE THREAD

**Issue by rhysied** [hashgraph/hedera-sdk-go#15]
Hi,

Noticed some odd behaviour when submitting CryptoTransfer transactions using the Go SDK.

For simple 1:1 transfers where the Operator is also the Sender, the following logic works assuming you have valid operator and recipient accounts set up, with the receipt showing status `SUCCESS` (22)

```
txnId, err := hedera.NewCryptoTransferTransaction().
			SetMaxTransactionFee(maxFee).
			AddSender(operatorAccount.AccountId, 10000).
			AddRecipient(recipient.AccountId, 10000).
			Execute(hederaClient)
```

When trying to handle the case where the Sender is not the operator but is a third party, automatic signing does not work, and using .Sign() instead of .SignWith() appears to throw `KEY_PREFIX_MISMATCH` errors as so:

*CASE 1* use .Sign() for the Sender and allow automatic operator signing as part of Execute() call (throws `KEY_PREFIX_MISMATCH` (68)):
```
txn := hedera.NewCryptoTransferTransaction().
		SetMaxTransactionFee(maxFee).
		AddSender(senderAccount, 10000).
		AddRecipient(recipientAccount, 10000).
		Build(hederaClient)

txnId, err := txn.Sign(senderAccount.PrivateKey).Execute(hederaClient)
``` 

*CASE 2* use .SignWith() for the Sender and allow automatic operator signing as part of Execute() call (throws `INVALID_SIGNATURE` (7)):
```
txn := hedera.NewCryptoTransferTransaction().
		SetMaxTransactionFee(maxFee).
		AddSender(senderAccount, 10000).
		AddRecipient(recipientAccount, 10000).
		Build(hederaClient)

txnId, err := txn.SignWith(senderAccount.PrivateKey, senderAccount.PrivateKey.Sign).Execute(hederaClient)
``` 

*CASE 3* use .SignWith() for the Sender and sign for the operator manually using .Sign() prior to the Execute() call (throws `KEY_PREFIX_MISMATCH` (68)):
```
txn := hedera.NewCryptoTransferTransaction().
		SetMaxTransactionFee(maxFee).
		AddSender(senderAccount, 10000).
		AddRecipient(recipientAccount, 10000).
		Build(hederaClient)

txnId, err := txn.SignWith(senderAccount.PrivateKey, senderAccount.PrivateKey.Sign).Sign(operatorAccount.PrivateKey).Execute(hederaClient)
``` 

*CASE 4* working case use .SignWith() for both the Sender and the operator (bypassing the automatic signing):
```
txn := hedera.NewCryptoTransferTransaction().
		SetMaxTransactionFee(maxFee).
		AddSender(senderAccount, 10000).
		AddRecipient(recipientAccount, 10000).
		Build(hederaClient)

txnId, err := txn.SignWith(senderAccount.PrivateKey, senderAccount.PrivateKey.Sign).SignWith(operatorAccount.PrivateKey, operatorAccount.PrivateKey.Sign).Execute(hederaClient)
```

So there are potentially two issues here:
1) Automatic operator signing not working as intended
2) using .Sign() throwing KEY_PREFIX_MISMATCH errors

If you need any more info please let me know.

Cheers, Rhys.

**Comment by mehcode** [comment]
This has been fixed on master. Thank you for the report. It was a simple typo in the `sign` function. It was rewritten in terms of `signWith` to prevent future discrepancies.
