### ISSUE TITLE
missing some entity memo getter/setter

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#151]
1. AccountCreateTransaction, no memo getter / setter, protobuf:
https://github.com/hashgraph/hedera-sdk-go/blob/b2f3ced77423d608f26eaddba557abafd2401f10/proto/CryptoCreate.proto#L51

2. TokenCreateTransaction, no memo getter, protobuf:
https://github.com/hashgraph/hedera-sdk-go/blob/b2f3ced77423d608f26eaddba557abafd2401f10/proto/TokenCreate.proto#L61

**Comment by andrix10** [comment]
Thank you, these have been added.
