### ISSUE TITLE
bug in durationFromProtobuf

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#161]
https://github.com/hashgraph/hedera-sdk-go/blob/509368b46a5a379b041d345632b92d124046d7a8/time.go#L14-L16

golang doc:

```
func Until(t Time) Duration
Until returns the duration until t. It is shorthand for t.Sub(time.Now()).
```

`durationFromProtobuf` treats the pb duration as `t` of type `time.Time`, and returns `t.Sub(time.now())`

**Comment by danielakhterov** [comment]
Was fixed by https://github.com/hashgraph/hedera-sdk-go/pull/164
