### ISSUE TITLE
Bug in TokenUpdateTransaction.SetExpirationTime

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#165]
https://github.com/hashgraph/hedera-sdk-go/blob/1e3e763d45bd3e36fe37d9a29166f309b21b167b/token_update_transaction.go#L202-L209

`expirationTime.UnixNano()` is not the nanos part of the timestamp, it's the nanos elapsed since epoch.

**Comment by danielakhterov** [comment]
You're right, not sure why we're doing the manual `proto.Timestamp` conversion when we have functions such as `timeToProtobuf()` already declared which do the conversion properly. We'll fix this with the next release.

**Comment by danielakhterov** [comment]
Closing as this has been resolved in https://github.com/hashgraph/hedera-sdk-go/pull/167
