### ISSUE TITLE
Balance.get () raise an error "missing required field: `payment`"

### ISSUE THREAD

**Issue by hs011** [hashgraph/hedera-sdk-go#18]
here ist my example-code
```
client, err := hedera.Dial("testnet.hedera.com:dddddddd")
if err != nil {
	panic(err)
}
defer client.Close()
myAccount := hedera.AccountID{Account: yyyyyyyy}
balance, err := client.Account(myAccount).Balance().Get()
if err != nil {
	panic(err)
}
```
what is the problem?

**Comment by mehcode** [comment]
Make sure you're on go 1.11+ and are just doing `go get github.com/hashgraph/hedera-sdk-go`. master should not be depended on. It's currently under flux.

**Comment by EugeneSindambiwe** [comment]
Hi guys,
it seems that the bug reported by @hs011 is either back or is reproducible under other cirumstances. I am using go1.12.5 windows/amd64 and have performed go get just now.
@mehcode any idea? @hs011: Was the issue possibly resolved differently than just updating the sdk? 
Thanks in avance, Eugene
