### ISSUE TITLE
transaction returning pre-check error?

### ISSUE THREAD

**Issue by pawmart** [hashgraph/hedera-sdk-go#2]
```
        client, err := hedera.Dial(<hostaddress>) // hostaddress
	accountID :=<accountID> // My public ID (4 numbers)
        operatorSecret, err := hedera.SecretKeyFromString(<string>) // My private key
	nodeAccountId := hedera.AccountID{Account: 3} // Should this be hardcoded?
	operatorAccountID := hedera.AccountID{Account: accountID}
	response, err := client.CryptoTransfer().
		Transfer(hedera.AccountID{Account: accountID}, -1).
		Transfer(hedera.AccountID{Account: accountID}, 1).
		Operator(operatorAccountID).
		Node(nodeAccountId).
		Memo(in.GetDescription()).
		Sign(operatorSecret). // Sign it once as operator
		Sign(operatorSecret). // And again as sender
		Execute()
```

This is my code to execute the transaction. It used to work just fine before the latest changes to 'master' regarding linux build changes.

I am now getting:

```
transaction failed the pre-check: InvalidTransaction
```

**Comment by gregscullard** [comment]
Which testnet are you seeing this on ? I may be able to look at the logs to identify the problem.
Also, I notice you're transferring -1/+1 to/from the same account. You can set those values to 0 (as long as the sum of +/- is 0, the network will accept your transaction).

**Comment by pawmart** [comment]
Thank you for your suggestion about 0 value transactions.

I am using `testnet.hedera.com:50125`

**Comment by gregscullard** [comment]
I'm seeing: "Signature validation failed for Payee Account in cryptoTransfer", also "Problem: start time is later than node local time!"

Looks like the signature validation were on the 24th, start time errors were today.

We had this issue with the java SDK whereby the start time for the transaction which is automatically generated is a few seconds ahead of the node's local time, the solution in the java sdk was to remove 10 seconds seconds from the start time so the transactionValidStart of the TransactionID was less likely to be ahead of the node's time if there are small differences.

Changing your client's local time to a few seconds earlier should temporarily fix this (until the SDK itself is updated)

**Comment by pawmart** [comment]
OK, It does not look like I am able to setup and customise docker container time. Is there alternative way of bypassing this 'start time' check or setting this up yourself?

Otherwise, I am unable to run the service inside docker.

**Comment by mehcode** [comment]
I've pushed an SDK update that does what @gregscullard mentioned and subtracts 10s from the timestamp before sending the transaction. If that was the issue, it should work now.
