### ISSUE TITLE
Issue with installing on mojave 10.14.2

### ISSUE THREAD

**Issue by coreman000** [hashgraph/hedera-sdk-go#20]
macair mojave 10.14.2
in terminal I've got:

     My-Comp:~ MyName$ go get github.com/hashgraph/hedera-sdk-go
    # github.com/hashgraph/hedera-sdk-go
    go/src/github.com/hashgraph/hedera-sdk-go/client.go:4:11: fatal error: 'hedera.h' file not found
     #include "hedera.h"
              ^~~~~~~~~~
    1 error generated.

also `go get -u github.com/hashgraph/hedera-sdk-go` gives the same

**Comment by gregscullard** [comment]
Hi, searching google for the error message gets this: 
https://stackoverflow.com/questions/20458796/unrecognized-import-path-with-go-get
and
https://github.com/lucas-clemente/quic-go/issues/1284

**Comment by coreman000** [comment]
After long searches  I've found out the problem:
1. git-lfs should be placed in reachable(by git) directory, best is `/usr/local/bin` (it seems to be a wide-known trap on macOS)
2. don't forget `git lfs install`
3. delete  `/hashgraph` , `/markbates` , `/mattn` directories from `~/go/src/github.com/` 
4. retry `go get github.com/hashgraph/hedera-sdk-go/`

**Comment by mehcode** [comment]
`brew install git-lfs` followed `git lfs install` should be enough as long as its done before `go get`. Glad you got it sorted.
