### ISSUE TITLE
Unable to build for Linux with latest version

### ISSUE THREAD

**Issue by KhoomeiK** [hashgraph/hedera-sdk-go#22]
I'm trying to run my Go implementation of Hedera Hashgraph on Debian 4.9.0-8-amd64 and I've tried a few things and am still getting errors. Running locally on my mac works perfectly fine which leads me to believe there's an issue with the x86_64-unknown-linux-musl/libhedera.a file.

Using the current master branch version, here's the error I get:
```
# github.com/hashgraph/hedera-sdk-go
/usr/bin/ld:/home/rohan/go/src/github.com/hashgraph/hedera-sdk-go/libs/x86_64-unknown-linux-musl/libhedera.a: file format not recognized; treating as linker script
/usr/bin/ld:/home/rohan/go/src/github.com/hashgraph/hedera-sdk-go/libs/x86_64-unknown-linux-musl/libhedera.a:1: syntax error
collect2: error: ld returned 1 exit status
```

My problem seemed similar to Issue #1, so I tried pulling 9de77ba and this is the error I get.
```
# github.com/hashgraph/hedera-sdk-go
/usr/bin/ld: cannot find -lhedera
collect2: error: ld returned 1 exit status
```

Anyone know what might be causing this other than a bug in libhedera?

**Comment by mehcode** [comment]
Note that Git LFS must be installed and configured  _before_ `go get ...`. I haven't found a reliable way to flush the go cache enough if you `go get` before configuring Git LFS. I recommend to `rm -rf $GOPATH`.
