### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by BourneLiu** [hashgraph/hedera-sdk-go#25]
when I execute the generate_key example, I got an error:
$> go run main.go
secret   = 302e020100300506032b6570042204205c09085bc46df159a1f5fdee5b6b0608b16aca744903dc4e719a41119e4576ff
mnemonic = laundry oblige scorpion lumber term nerve tuna upset few exclude sense real month fiscal identify always script bleak father senior stone city brass sister
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x490ce1]

runtime stack:
runtime.throw(0x6ae0b5, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x490c90, 0xc000057de0, 0x1)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000057db0 sp=0xc000057d78 pc=0x40a93e
github.com/hashgraph/hedera-sdk-go._Cfunc_hedera_public_key_from_secret_key(0xc000014180, 0x2312361254997, 0x1ace9d60d2be8, 0x18faf7e592df6, 0xca4cbdd701e2)
	_cgo_gotypes.go:450 +0x4e fp=0xc000057de0 sp=0xc000057db0 pc=0x48f86e
github.com/hashgraph/hedera-sdk-go.SecretKey.Public(0x59f16dc45b08095c, 0x8066b5beefdf5a1, 0x4edc034974ca6ab1, 0xff76459e11419a71, 0x0, 0x0, 0x0, 0x0)
	/home/dev01/go/src/github.com/hashgraph/hedera-sdk-go/crypto.go:49 +0x66 fp=0xc000057e58 sp=0xc000057de0 pc=0x48ff46
main.main()
	/home/dev01/go/src/github.com/hashgraph/hedera-sdk-go/examples/generate_key/main.go:13 +0x1c4 fp=0xc000057f98 sp=0xc000057e58 pc=0x490974
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000057fe0 sp=0xc000057f98 pc=0x430fd7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x459281
exit status 2

$> go version
go version go1.11.5 linux/amd64
$> cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

Who can tell me the causes? thanks.

**Comment by kenthejr** [comment]
Hey Bourne. I'm going to first recommend that @mehcode rebuild the Linux artifact and test the key gen piece. I know the rest of it is working in Debian, but I'm not sure it's been tested on CentOS (though I'm not sure there is much difference).

**Comment by seanybaggins** [comment]
@BourneLiu I am having the same issue. Just out of curiosity, what hardware is your OS running on? I am using GalliumOS on an Asus Chromebook c302 flip. Here is my information regarding this problem.

### What version of Go are you using (`go version`)?
```txt
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/Sean/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/Sean/Dropbox/Research"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451736839=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
Attempted to run the following program using the hedera hashgraph go sdk.
```go
package main

import (
	"fmt"

	"github.com/hashgraph/hedera-sdk-go"
)

func main() {
	secret, _ := hedera.GenerateSecretKey()

	fmt.Printf("Proof this line is printing.\n")

	public := secret.Public()

	fmt.Printf("public   = %v\n", public)
}

```

### What did you expect to see?
```txt
Proof this line is printing.
public   = aBunchOfNumbers
```

### What did you see instead?
```txt
Proof this line is printing.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x652bd3]

runtime stack:
runtime.throw(0x6ae516, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x4910b0, 0xc000038640, 0x1)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000038610 sp=0xc0000385d8 pc=0x40ae7e
github.com/hashgraph/hedera-sdk-go._Cfunc_hedera_public_key_from_secret_key(0xc0000161e0, 0x62ad80abe23ed, 0x20dff79ceacd5, 0x1bc391460852d, 0x17de07be442d9)
        _cgo_gotypes.go:450 +0x4e fp=0xc000038640 sp=0xc000038610 pc=0x48fdae
github.com/hashgraph/hedera-sdk-go.SecretKey.Public(0x40964715b4e53414, 0x614e508bbaa7853f, 0x8276fd839d5589b6, 0x62cfae0d1f6003a9, 0x0, 0x0, 0x0, 0x0)
        purposelyOmmitedDirectoryName/src/github.com/hashgraph/hedera-sdk-go/crypto.go:49 +0x66 fp=0xc0000386b8 sp=0xc000038640 pc=0x490486
main.main()
        purposelyOmmitedDirectoryName/src/Generate Keys/keys.go:14 +0xa9 fp=0xc000038798 sp=0xc0000386b8 pc=0x490d99
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0000387e0 sp=0xc000038798 pc=0x431517
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000387e8 sp=0xc0000387e0 pc=0x4597c1
exit status 2
```

I believe the Public() function is making a cgocall that ultimately is causing a segfault.

**Comment by tshear** [comment]
secret, _ := hedera.GenerateSecretKey()
should be
secret := hedera.GenerateSecretKey()
hedera.GenerateSecretKey() returns only one variable.

**Comment by seanybaggins** [comment]
@tshear I don't think
`secret, _ := hedera.GenerateSecretKey()`
should be 
`secret := hedera.GenerateSecretKey()`

The function is defined to return a SecretKey and another string.
```go
func GenerateSecretKey() (SecretKey, string) {
	return GenerateSecretKeyWithPassword("")
}
```

**Comment by tshear** [comment]
Sorry, comment wrong. Was working with wrong sdk version.

**Comment by seanybaggins** [comment]
@tshear Totally good

**Comment by mehcode** [comment]
I'll look into this today. Can you all try older versions and see if it happens?

https://github.com/hashgraph/hedera-sdk-go/releases

**Comment by seanybaggins** [comment]
@mehcode I will be sure to do this. Might be a day till I get the time to do it though :(

**Comment by tshear** [comment]
Ryan:
  

I had originally used a version built on Thursday, ?November ?29, ?2018, ??7:26:51 AM.  

It had one return variable and didn't crash.  

     

   
----------------------------------------
 DataparencyT  Timothy A. Shear, CEO
 Dataparency, LLC
 (248) 390-5566

  

----------------------------------------

**Comment by seanybaggins** [comment]
@mehcode So I just tested it with v0.2.0. Worked fine without a segfault. Can I continue to develop on this version?

**Comment by mehcode** [comment]
Go ahead. It's clearly a regression with v0.3 then. We need to setup Travis for this repo.

**Comment by mehcode** [comment]
This is fixed with `0.3.1`. Update with `go get -u github.com/hashgraph/hedera-sdk-go`.

**Comment by BourneLiu** [comment]
Sorry for the late reply because we were having our Chinese New Year festival.

I'm so glad that you have solved the problem. I have updated the package to 0.3.1, but when I execute the generate_key example, I got an error again. This time the error message is a little bit different from the last one. I will go ahead with the old version and meanwhile hope you can look at the problem.

We can see the package version from the changelog to confirm that I have already updated the package to the 0.3.1:
`# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## 0.3.1 - 2019-02-06

### Fixed

 - `hedera.SecretKey.Public()` now uses the correct definition of the PublicKey structure [#25](https://github.com/hashgraph/hedera-sdk-go/issues/25)

## 0.3.0 - 2019-01-07`

And the error message is:
`secret   = 302e020100300506032b6570042204209e2e415df3f358815b3d6c5b720d1d4b892344ebe81c60fb798bef27187cfc66
mnemonic = abstract spike prosper woman engage mask hour enhance agree citizen pupil gift canal special success pen comic price better card room sail daring can
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x490ce1]

runtime stack:
runtime.throw(0x6ae2f5, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x490c90, 0xc000057de0, 0x1)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000057db0 sp=0xc000057d78 pc=0x40a93e
github.com/hashgraph/hedera-sdk-go._Cfunc_hedera_public_key_from_secret_key(0xc000014180, 0x48abc5c027ad6, 0x5d66f3221a785, 0x399daeece51a9, 0x7e2b6c480d64e)
	_cgo_gotypes.go:450 +0x4e fp=0xc000057de0 sp=0xc000057db0 pc=0x48f86e
github.com/hashgraph/hedera-sdk-go.SecretKey.Public(0x8158f3f35d412e9e, 0x4b1d0d725b6c3d5b, 0xfb601ce8eb442389, 0x66fc7c1827ef8b79, 0x0, 0x0, 0x0, 0x0)
	/home/dev01/go/src/github.com/hashgraph/hedera-sdk-go/crypto.go:49 +0x66 fp=0xc000057e58 sp=0xc000057de0 pc=0x48ff46
main.main()
	/home/dev01/main.go:13 +0x1c4 fp=0xc000057f98 sp=0xc000057e58 pc=0x490974
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000057fe0 sp=0xc000057f98 pc=0x430fd7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x459281
exit status 2`

`$> go version
go version go1.11.5 linux/amd64
$> cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)`

Looking forward your reply.

**Comment by seanybaggins** [comment]
@BourneLiu I had to remove one file in addition to updating my repo to work. 
Here is the directory of and file that I needed to delete.

pkg/linux_amd64/github.com/hashgraph/hedera-sdk-go.a

**Comment by BourneLiu** [comment]
> @BourneLiu I had to remove one file in addition to updating my repo to work.
> Here is the directory of and file that I needed to delete.
> 
> pkg/linux_amd64/github.com/hashgraph/hedera-sdk-go.a

Just out of curiosity how can you find the file, blew is my directory structure:
> ll go/src/github.com/hashgraph/
    total 4
    drwxr-xr-x 7 nobody nobody 4096 Feb 12 19:05 hedera-sdk-go

I can't find the file use find directive too:
> find go/src/github.com -type f -name "hedera-sdk-go.a"

and nothing returnd

**Comment by seanybaggins** [comment]
@BourneLiu I think you are searching through go/src when you should be searching through go/pgk

**Comment by BourneLiu** [comment]
> @BourneLiu I think you are searching through go/src when you should be searching through go/pgk

Thanks, you are right, I search through a wrong path. It works after I delete the file.
