### ISSUE TITLE
Regression TokenCreateTransaction.GetExpiryTime

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#276]
https://github.com/hashgraph/hedera-sdk-go/blob/e09a07ac6019e29eaa832229a7205f376976f994/token_create_transaction.go#L476

If the expiry is set to 1, GetExpiryTime will return 2

**Comment by xin-hedera** [comment]
same issue here:

https://github.com/hashgraph/hedera-sdk-go/blob/de79d70a7cf2820f7415f69038131c8c5ab6ddef/token_update_transaction.go#L238

**Comment by andrix10** [comment]
i thought i looked up anything close to this bug, but i guess not
