### ISSUE TITLE
Rpc error code when getting receipt or submitting transaction

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#318]
### Description

Rarely, when a transaction is submitted or getting its receipt, the sdk resolves with the following error:
`retry 2/10: rpc error: code = Internal desc = server closed the stream without sending trailers`.

### Steps to reproduce

1. Submitting a scheduled transaction (create/sign)
2. Getting a scheduled transaction's receipt

### Additional context

[0.0.540268@1636760423.606141123]. Error: [retry 2/10: rpc error: code = Internal desc = server closed the stream without sending trailers]

### Hedera network

mainnet

### Version

v2.1.5

### Operating system

Linux

**Comment by danielakhterov** [comment]
I believe this was because the network was going down inconsistently during the weekend.

**Comment by failfmi** [comment]
This has occurred yesterday on testnet for a long time.
