### ISSUE TITLE
Regression TransferTransaction.GetTokenTransfers returns nft transfers

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#320]
https://github.com/hashgraph/hedera-sdk-go/blob/5eb38d215e6ec3a2f81111322eb7b51a238c668a/transfer_transaction.go#L104-L114

Should return fungible token transfers.

**Comment by danielakhterov** [comment]
I think the issue here is `len(tokenTransfer.nftTransfesr) > 0` which should simply be `len(tokenTransfer.transfers) > 0`. Nonetheless, definitely an issue.
