### ISSUE TITLE
Getting receipt returns the wrong status

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#326]
### Description

Transaction Receipt for `0.0.540268@1637230312.373622714` resolved with `FAIL_INVALID`, when the actual status is
[IDENTICAL_SCHEDULE_ALREADY_CREATED](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.540268-1637230312-373622714).

It has never occurred before. Can it be related to a node not being synced correctly?

### Steps to reproduce

.

### Additional context

![image](https://user-images.githubusercontent.com/20928965/142455999-6cb36c8b-b0d3-4038-ba90-73c79e69eb83.png)

### Hedera network

mainnet

### Version

v2.1.5

**Comment by danielakhterov** [comment]
Um, I'm a bit lost for words here. We map `ResponseCodeEnum` to `Status` as 1-to-1 so unless we somehow are incorrectly mapping these types I'm going to guess this is an issue with the nodes themselves.

**Comment by SimiHunjan** [comment]
@tinker-michaelj ^

**Comment by danielakhterov** [comment]
Stale issue
