### ISSUE TITLE
Regression - TransferTransaction freezeError is set when parsed from previously serialized signed transaction bytes

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#338]
### Description

Given the serialized bytes of an already signed TransferTransaction, parsing it with `hedera.TransactionFromBytes`, and then trying to execute will return `errTransactionIsFrozen`.

The problem is in _TransferTransactionFromProtobuf, `tx.AddHbarTransfer` is called to rebuild the hbar transfers from the protobuf, and the side effect of the call is `_RequireNotFrozen()` which sets `tx.freezeError`

### Steps to reproduce

please refer to the bug description.

### Hedera network

testnet

### Version

\>= v2.5.1

**Comment by andrix10** [comment]
I tried reproducing this but so far everything works as expected.

Here is some new tests I added: [https://github.com/hashgraph/hedera-sdk-go/pull/339/files#diff-d71e08dc04c1dd956de5e4da0fd6c1946c3ac357cbb33a917f842df79cabb300R119](tests)

**Comment by xin-hedera** [comment]
v2.6.0 has some changes and in _TransferTransactionFromProtobuf there is no more `tx.AddHbarTransfer` call. If you switch to v2.5.1 you'll hit the issue.

**Comment by andrix10** [comment]
Yep we reverted back, and just implemented proper ordering. As its not an issues anymore I will be finally closing this.
