### ISSUE TITLE
Test SDK retry enhancements do improve handling down nodes 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#341]
### Problem

The following issues were added to increase the stability and performance of the SDKs when nodes are unavailable.

https://github.com/hashgraph/hedera-sdk-go/issues/333
https://github.com/hashgraph/hedera-sdk-go/issues/332
https://github.com/hashgraph/hedera-sdk-go/issues/329

After the enhancements are implemented, the SDK needs to be tested against an environment that has unavailable nodes in the network.

### Solution

- Add a few invalid node entries
- Set-up HAproxy that isn't routing

**Comment by xin-hedera** [comment]
As part of the improvement, can we remove the blocking 10s wait on grpc node channel creation?
