### ISSUE TITLE
Panic in TransferTransaction.AddTokenTransferWithDecimals

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#385]
https://github.com/hashgraph/hedera-sdk-go/blob/4a62ef7de770b996b998353d43e3d5e32b7e9720/transfer_transaction.go#L149

```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
```

The problem is `TransferTransaction.expectedDecimals` is not properly initialized.

**Comment by danielakhterov** [comment]
Fixed on `develop`: https://github.com/hashgraph/hedera-sdk-go/commit/3def3ac1c764b6a93c34a5c30a9fc780e6722096
