### ISSUE TITLE
Requests are not cycling though nodes

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-go#386]
We have a report stating we are not incrementing next node index appropriately. Can we investigate this and add a regression test.

**Comment by failfmi** [comment]
[Here](https://github.com/LimeChain/hedera-sdk-go/blob/debug/retry-investigation/examples/test/main.go) is an example of how I am testing it. Basically, set 1 100% failing node, and every time it's that node's time to execute, it tries 10 times and then does not increment the node selection index and ends the whole execution of the transaction.

The version of the sdk is a forked version of 2.6.0, which has an additional logs just for debugging.

**Comment by failfmi** [comment]
![image](https://user-images.githubusercontent.com/20928965/151506488-5e07041a-8fdb-4c6b-bd9f-f7fd7cfe9974.png)

**Comment by danielakhterov** [comment]
After looking into this @andrix10 and I have found out the issue. Firstly I'd like to mention we do retry on `ResourceExhausted` when it's returned by the node, but what is happening here is the node is not even connecting (which is treated differently and fails in a different place). Since the node fails to connect the `advanceRequest()` function is not called and hence the same node is re-selected. Anyways, thanks for pointing this out, it definitely is an issue, and thanks in particular for that picture as it quickly indicated where the error was actually coming from. I am curious though as to how to test this; we have mocking servers setup, but I don't know how we can make the mocking servers hold a connection that is attempting to connecting without completing the connecting process.
