### ISSUE TITLE
`ContractID._ToProtobuf()` treats `evmAddress` inconsistently with `ContractIDFromString()`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-sdk-go#400]
### Description

I used `ContractIDFromString()` to convert a `0.0.X` string literal to a `ContractID`.

Although a contract with this id was extant, a subsequent `NewContractCallQuery()` got `INVALID_CONTRACT_ID` using the `ContractID`.

### Steps to reproduce

Use `ContractIIDFromString()` to convert a `string` to a `ContractID`, try to use it in a `ContractCallLocal` query.

### Additional context

- The problem is that `ContractIDFromString()`, when given a `0.0.X` literal, [initializes `evmAddress` to an empty `[]byte{}`](https://github.com/hashgraph/hedera-sdk-go/blob/main/contract_id.go#L38).
- ⚠️ But `ContractID._ToProtobuf()` creates its `0.0.<evm_address>` form [**whenever `evmAdress` is not `nil`**](https://github.com/hashgraph/hedera-sdk-go/blob/main/contract_id.go#L171).
- Since `[]byte{}` is not `nil`, a `ContractID` deserialized from a `0.0.X` literal leads to `0.0.<>` being sent to the node---which is certainly invalid.

### Hedera network

other

### Version

v2.9.0

**Comment by andrix10** [comment]
Thank you, it's a small bug, but can be pretty significant.
