### ISSUE TITLE
Add more unit tests for new features

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#465]
### Problem

As we add new features to the SDK we have been encountering regression type issues. We should identify ways to try and help prevent these kinds of issues happening in the future.

### Solution

- [ ] Have simple tests than just call every single method on each type. That way we'd know of something breaks.
- [ ] Add an external signing test
- [ ] Existing tests set the node. We should have a bit more tests that don't.

**Comment by danielakhterov** [comment]
Blocked on #546
