### ISSUE TITLE
client NewContractCallQuery() call on existing contract seems to hang while given MaxGas>throttle instead of MAX_GAS_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#466]
### Description

Running on a fresh reset v0.25.0 build with default smart contract throttles: 5M/node and 15M/network.

The client code calls `NewContractCallQuery()` on an ERC20 contract's name() function.

While gives MaxGas = 6M, the client will fail with `MAX_GAS_LIMIT_EXCEEDED` as expected.

Whence a contract is created, next call the client attempts to use the existing contract to call `NewContractCallQuery()` on the `name()` function given MaxGas=6M, it would hang and eventually would fail with
```
string=exceptional precheck status TRANSACTION_EXPIRED
```

I think the LocalCall has separate Gas throttle applied, but never the less the client expects anything other than a timeout error.  Same client runs with no issues if given a valid MaxGas=5M, so the invalid MaxGas led the process of the tx into an erroneous code path.

### Steps to reproduce

1. Create a smart contract with a state variable name="testname"
2. A function(name) to return the state variable
3. NewContractCallQuery("name", nil).SetGas(5000000) should return "testname"
4. NewContractCallQuery("name", nil).SetGas(6000000) should return error `MAX_GAS_LIMIT_EXCEEDED`

Test #2
1. Use the above created smart contract
2. NewContractCallQuery("name", nil).SetGas(5000000) should return "testname"
3. NewContractCallQuery("name", nil).SetGas(6000000) would hang for awhile and fail with
```
string=exceptional precheck status TRANSACTION_EXPIRED
```

### Additional context

Build: v0.25.0
Golang 1.17
hedera-sdk-go v2.11.0-beta.1

### Hedera network

other

### Version

v2.11.0-beta.1

### Operating system

Linux

**Comment by danielakhterov** [comment]
@tomzhenghedera can you enable logging to see what status we're getting from Hedera. If you look at the `executable.go` you should see how to enable logging.

**Comment by tomzhenghedera** [comment]
sure. will get to it and report.
