### ISSUE TITLE
NewContractCreateTransaction() failed to create contract with CONTRACT_REVERT_EXECUTED

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#499]
### Description

It appears the latest release has a regression on creating contract, with latest releases, `v2.14.0`, `v2.14.0-beta.3`, and `v2.13.4`, the following code segment would fail with `CONTRACT_REVERT_EXECUTED`.

The code had been working at `v2.11.0-beta.1` and prior releases.  line 18-23 in below code is redundant just trying to demonstrate different ways to get the new contract ID(now it fails w/ `CONTRACT_REVERT_EXECUTED`)

There could be changes in how to obtain created contract ID, if so, please let me know.  As well as how to obtain `ContractResults`.

```go
  1 
  2     // Instantiate the contract instance
  3     contractTransactionID, err := hedera.NewContractCreateTransaction().
  4         SetProxyAccountID(client.GetOperatorAccountID()).
  5         SetInitialBalance(hedera.NewHbar(36)).
  6         SetNodeAccountIDs([]hedera.AccountID{node}).
  7         SetMaxTransactionFee(hedera.NewHbar(feeMax)).
  8         SetGas(gasCapMax).
  9         SetBytecodeFileID(fid).
 10         SetAdminKey(client.GetOperatorPublicKey()).
 11         Execute(client)
 12 
 13     if err != nil {
 14         log.Errorf("new_contract: tx %v", err.Error())
 15         return hedera.ContractID{}, err
 16     }
 17 
 18     receipt, err := contractTransactionID.GetReceipt(client)
 19     if err != nil {
 20         log.Errorf("new_contract: GetReceipt: %v", err.Error())
 21         return hedera.ContractID{}, err
 22     }
 23     cid = *receipt.ContractID
 24 
 25 
 26     contractRecord, err := contractTransactionID.GetRecord(client)
 27     if err != nil {
 28         log.Errorf("new_contract: GetRecord %v", err.Error())
 29         return hedera.ContractID{}, err
 30     }
 31 
 32     contractCreateResult, err := contractRecord.GetContractCreateResult()
 33     if err != nil {
 34         log.Errorf("new_contract: GetResult %v", err.Error())
 35         return hedera.ContractID{}, err
 36     }
 37 
 38     cid = *contractRecord.Receipt.ContractID
 39 

```

## Sample program

 tar gz file with sample code

[file-append.gz](https://github.com/hashgraph/hedera-sdk-go/files/8706094/file-append.gz)

To reproduce

```shell
# ./file-append -network=previewnet -file Callee.bin
# ./file-append -network=previewnet -file ERC20.bin
```

`Callee.sol` solidity code is included and `compile.sh` has the steps used to generate BIN code `Callee.bin`

Example output while running w/o `line 18-23`

```shell
./file-append -network=previewnet -file Callee.bin 
01:58:15.656 INFO network = [previewnet]
01:58:15.657 INFO file    = [Callee.bin]
01:58:15.658 INFO size    = [4096]
01:58:15.659 INFO fee     = 10
01:58:15.660 INFO gas     = [60000] 60000
01:58:15.661 INFO gascap  = [600000] 600000
01:58:15.662 INFO Connected to [previewnet] network and mirror node [[hcs.previewnet.mirrornode.hedera.com:5600]]
01:58:15.665 INFO get_file[Callee.bin]: contract bytecode size: [896] bytes
01:58:18.713 INFO get_file: New file ID = [0.0.27668]
01:58:20.369 ERROR new_contract: GetRecord exceptional receipt status: CONTRACT_REVERT_EXECUTED
```

Example output while running with `line 18-23`

```shell
./file-append -network=previewnet -file ERC20.bin 
02:02:30.039 INFO network = [previewnet]
02:02:30.041 INFO file    = [ERC20.bin]
02:02:30.041 INFO size    = [4096]
02:02:30.042 INFO fee     = 10
02:02:30.042 INFO gas     = [60000] 60000
02:02:30.043 INFO gascap  = [600000] 600000
02:02:30.044 INFO Connected to [previewnet] network and mirror node [[hcs.previewnet.mirrornode.hedera.com:5600]]
02:02:30.046 INFO get_file[ERC20.bin]: contract bytecode size: [14930] bytes
02:02:37.810 INFO get_file: New file ID = [0.0.27670]
02:02:39.395 ERROR new_contract: GetReceipt: exceptional receipt status: CONTRACT_REVERT_EXECUTED
02:02:41.032 ERROR new_contract: GetReceipt: exceptional receipt status: CONTRACT_REVERT_EXECUTED
```

### Hedera network

previewnet

### Version

v2.14.0

### Operating system

Linux

**Comment by tomzhenghedera** [comment]
Switched to use `ContractCreateFlow()` looks like working for the moment, allows the contract being created.

To create smart contract via `NewContractCreateTRansaction()` method, as documented in [here](https://docs.hedera.com/guides/docs/sdks/smart-contracts/create-a-smart-contract) seems to be broken.  

This leads to following Qs:
- how a client gets the bytecode FileID used to create the smart contract
- how to obtain `ContractCreateResults` information like `GasUsed`

**Comment by andrix10** [comment]
I looked into it yesterday, I am so far not sure its SDK problem. Both of your smaller files worked if you don't set initial balance.

**Comment by tomzhenghedera** [comment]
You're right.  I tried to disable the `SetInitialBalance` and the code passed on both `v0.25.3` and `v0.26.0`.  Let me check with eng and report back.

**Comment by tomzhenghedera** [comment]
The cause that failed while calling with `SetInitialBalance ` API is due to the contract needs to have a constructor with `payable` modifier.

I think the ticket could be closed.  Thanks!

**Comment by andrix10** [comment]
Alright, no problem.
