### ISSUE TITLE
Expanded Examples/Direction?

### ISSUE THREAD

**Issue by johnsampson** [hashgraph/hedera-sdk-go#5]
Can you expand your examples and/or README to include a few lines at the top of each example file with more details on the commands to get to a basic `hello world`?

I ask as I believe I'm doing things correctly.  I have generated private/public keys and am trying to pass private key to `create account`, but get the following error:

**Command:**
> `OPERATOR_KEY=_302[...]94c_ run examples/create_account/main.go`

**Error:**
> `panic: INVALID_SIGNATURE` on `/examples/create_account/main.go:44`

**Comment by mehcode** [comment]
For sure. Note that each example requires an `OPERATOR_ID` and `OPERATOR_KEY` to be set. The key must be an (optionally-prefixed) ed25519 private key. 

---

I'll see about adding a "running the examples" section to the README

**Comment by mehcode** [comment]
@johnsampson Turns out our examples just hard-coded an account ID of 2.

```bash
❯ export OPERATOR_ID=0.0.142125
❯ export OPERATOR_KEY=302e020100300506...
❯ go run ./examples/create_account/main.go                                                                            
```

or

```bash
❯ env OPERATOR_ID=0.0.142125 OPERATOR_KEY=302e020100300506... go run ./examples/create_account/main.go                     
```

**Comment by mehcode** [comment]
There are now significantly more examples. Please re-open if you still need help.
