### ISSUE TITLE
transaction.signWithOperator will panic on nil operator.privateKey

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#53]
When a Client is setup with SetOperatorWith, it's operator.PrivateKey will be nil, this will cause transaction.signWithOperator panic at the line below:

https://github.com/hashgraph/hedera-sdk-go/blob/c2c538fc834e2be1b26fc5a9fc62e2fc68948f71/transaction.go#L46

**Comment by QuestofIranon** [comment]
Xin, please check #56 . It should fix this panic.
