### ISSUE TITLE
Transfering ERC-20 tokens

### ISSUE THREAD

**Issue by silverstr89** [hashgraph/hedera-sdk-go#534]
### Description

In solidity i have some sample of code

        require(token.balanceOf(address(msg.sender)) >= (_amount), "Not enough");
        require(token.transferFrom(address(msg.sender), hotWallet, ( _amount)), "cannot transfer");

before i called approve and it is ok

when i trying to call function which transfering ERC-20, i got error "Reverted". and problem is definetly in hedera, because in ethereum it works fine

### Steps to reproduce

create any function which contains transfering tokens

        require(token.balanceOf(address(msg.sender)) >= (_amount), "Not enough");
        require(token.transferFrom(address(msg.sender), hotWallet, ( _amount)), "cannot transfer");

call it from hedera sdk like a 

	tx, err := hed.NewContractExecuteTransaction().
		SetContractID(c.id).
		SetGas(1_000_000).
		SetFunction("call", params).
		Execute(c.client)

### Hedera network

testnet

### Version

2.16.0

**Comment by danielakhterov** [comment]
Can you add the snippet for your `params` and also what the function signature for `call` is.

**Comment by silverstr89** [comment]
```
params, err := hed.NewContractFunctionParameters().
		AddAddress(to.ToSolidityAddress())
	if err != nil {
		return err
	}
	params = params.
		AddUint256(id.Bytes()).
		AddUint256(amount.Bytes())
```


```
function mint(
        address _to,
        uint256 _id,
        uint256 _amount
    ) public 
```

**Comment by danielakhterov** [comment]
In the above code you're setting the function name to be `call`, but in the solidity code the function is called `mint`. Perhaps changing that would fix the issue?

**Comment by silverstr89** [comment]
no, it is mint, i copied wrong

**Comment by silverstr89** [comment]
I'm trying to write function which will be transfer erc-20 tokens in hedera hashgraph.

```
contract Coins is ERC20 {
    constructor(string memory name_, string memory symbol_)  ERC20(name_, symbol_) {
        _mint(msg.sender, 1000000000000000000000);
    }
}
```

very simple solidity contract

then i deploy it in hedera

```
tx, err := hedera.NewContractCreateFlow().
        SetBytecode(bytecode).
        SetGas(1_000_000).
        SetConstructorParameters(
            hedera.NewContractFunctionParameters().
                AddString("Coins").
                AddString("coin"),
        ).
        Execute(client)
```

then i've trying to transfer some erc-20 tokens to other address

```
ps, _ := hedera.NewContractFunctionParameters().
    AddAddress("0.0.34937758")
ps.AddUint256(big.NewInt(1).Bytes())

contractExecTx, err := hedera.NewContractExecuteTransaction().
    SetContractID(newContractID).
    SetGas(1000000).
    SetFunction("transfer", ps).
    Execute(client)
```


and i got error StatusContractRevertExecuted (33)

so i cannot transfer erc-20 tokens as it is

is it possible to use ERC-20 tokens as a usual in Ethereum? or i have to use HTS only? is it possible to use solidity contract and register it as token in Hedera?

thank you so much

**Comment by danielakhterov** [comment]
I'm going to cc @shemnon as he understands smart contracts much better than I. However, from my understanding you can only transfer HTS tokens over smart contracts over.

**Comment by silverstr89** [comment]
hold on, my solidity very simple

```
pragma solidity ^0.8.7;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";    
contract Coins is ERC20 {
        constructor(string memory name_, string memory symbol_)  ERC20(name_, symbol_) {
            _mint(msg.sender, 1000000000000000000000);
        }
    }

```
what it is wrong with that? just transfer and thats it

**Comment by silverstr89** [comment]
**UPD: solution**

looks like bytes for uint256 not compatible with hedera uint256

i've takes some abi lib

```
github.com/dcb9/go-ethereum/accounts/abi


AddUint256(abi.U256(big.NewInt(some number)))
```


and back to big.Int


```
query.GetUint256(0) // query for getting uint256

bInt := new(big.Int)
bInt.SetBytes(query.GetUint256(0))
```

and now it is works perfect

**Comment by danielakhterov** [comment]
Closing this in favor of #537
