### ISSUE TITLE
Improve SDK documentation

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#551]
### Problem

Add documentation for classes and methods.

### Solution

Add documentation for classes and methods.

**Comment by Petyo-Lukanov** [comment]
Hey @SimiHunjan , 
Since we have these in place can we consider this issue completed or the purpose of this task is different? 
- https://github.com/hashgraph/hedera-sdk-go/pull/737
- https://github.com/hashgraph/hedera-sdk-go/pull/743
- https://github.com/hashgraph/hedera-sdk-go/pull/744

Thanks!
