### ISSUE TITLE
wrong check in TokenUpdate

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#552]
### Description

https://github.com/hashgraph/hedera-sdk-go/blob/main/token_update_transaction.go#L398
and
https://github.com/hashgraph/hedera-sdk-go/blob/main/token_update_transaction.go#L475
has to be
```
	if transaction.kycKey != nil {
		body.KycKey = transaction.kycKey._ToProtoKey()
	}
```

### Steps to reproduce

Try updating a token's admin key, which has no kyc key.

### Hedera network

mainnet

### Version

v2.17

### Operating system

macOS

**Comment by danielakhterov** [comment]
The result of copying and pasting code, heh. Will get this fixed before release today.
