### ISSUE TITLE
client.setOperatorWith requests two signatures when one is expected

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-go#565]
### Description

I've setup an example use of client.setOperatorWith which builds a transaction with a single node set in `SetNodeAccountIds`, yet the callback for the signature is executed twice.

Have tried to set a transactionId, freeze the transaction, with `Freeze()` and `FreezeWith()` and the result is the same, two signature requests when only one is expected.

Note, this happens before .getReceipt, so it's not the receipt causing the second signature request (that doesn't ask for one).

### Steps to reproduce

See example attached (rename to `.go`)
[main.txt](https://github.com/hashgraph/hedera-sdk-go/files/9444583/main.txt)

### Hedera network

testnet

### Version

v2.17.1

### Operating system

macOS

**Comment by andrix10** [comment]
Sorry I forgot to reply yesterday, the second signing is because we do a build all for transaction hash in transaction response which also signs it again.

**Comment by gregscullard** [comment]
Can this be fixed somehow, trying to get the transactions signed via a signer (client.setOperatorWith(...)) which results in the external signer being prompted to sign the transaction twice.
The signer in this instance is a hardware wallet... so the end user is asked to sign twice which doesn't make sense.

**Comment by andrix10** [comment]
Alright, that does seem bad, will discuss with Daniel what to do about this.

**Comment by danielakhterov** [comment]
@andrix10 I don't remember exactly how the Go SDK functions, but I'm guessing we build transactions on demand, but don't cache them for later in case we get the same node account ID.
