### ISSUE TITLE
`AliasEvmAddress` field in `AccountID` does not serialize or deserialize correctly

### ISSUE THREAD

**Issue by Sean-Tedrow-LB** [hashgraph/hedera-sdk-go#567]
### Description

Copy/pasted from https://github.com/hashgraph/hedera-sdk-java/issues/1112

I have gotten confirmation that the `AliasEvmAddress` field in `AccountID` should serialize as the literal bytes of the `EvmAddress`, but instead it serializes as the bytes of a `Key` proto message with the `ECDSA_secp256k1` field filled with the bytes of the `EvmAddress`

### Steps to reproduce

Look at the source code

### Hedera network

other

### Version

current version

**Comment by andrix10** [comment]
I think this was fixed along with alias update pr.
