### ISSUE TITLE
TransactionFromBytes doesn't set memo

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#570]
### Description

The function `TransactionFromBytes` doesn't set the memo field when there is memo in the serialized protobuf bytes

### Steps to reproduce

1. build a transaction with memo
2. freeze
3. `TransactionToBytes`
4. `TransactionFromBytes`
5. `TransactionGetTransactionMemo` returns empty memo

### Hedera network

mainnet, testnet, previewnet

### Version

main

**Comment by andrix10** [comment]
Good catch, need to go through and make sure everything else is set.
