### ISSUE TITLE
NewAccountBalanceQuery no longer provides token balances (as per HIP367), but mirrors are not ready

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-go#589]
### Description

After already modifying Wallawallet to use the mirror node for obtaining token balances (because of HIP367), we were advised by @gregscullard at Swirlds last week to revert back to using the Hedera node's balance query because all mirror nodes won't be ready in time to support token balances. The issues with the mirror nodes that we are seeing are:

1. Token balance data lags by up to 15 minutes.
2. There is no proper API yet to retrieve and page through all unlimited token balances. Greg referred me to this open issue: https://github.com/hashgraph/hedera-mirror-node/issues/4142 Currently we can only show up to 50 tokens.

I am unable to follow Greg's advice, because the latest versions of the Hedera golang SDK (v2.17.1 and v2.17.5) no longer return the token/decimal balance info. If I revert back to 2.16.0 it's there, but I then add risk to breaking other features that we have added to our app since regarding NFT and staking support.

Example balance query results for account 0.0.238578 on mainnet:

Golang SDK 2.16.0:

` {"balance":5241469331,"tokens":{"0.0.127877":100000000,"0.0.456858":0,"0.0.583572":0,"0.0.629591":0,"0.0.635877":0},"decimals":{"0.0.127877":8,"0.0.456858":6,"0.0.583572":0,"0.0.629591":6,"0.0.635877":4}}`

Golang SDK 2.17.5:

` {"balance":5241469331,"tokens":{},"decimals":{}}`

We are currently in open beta and would like to go to production as early as Monday, October 17 2022. Can you please advise us or provide us quickly with a release build that brings back the token balance/decimal result data for NewAccountBalanceQuery until Hedera/Swirlds is ready to deprecate the functionality (which according to Greg is 6 months after all mirror nodes are able to provide token balance data that HIP367 deprecates)?

### Steps to reproduce

1. Create an account and move some tokens to it.
2. Attempt to use the golang SDK's NewAccountBalanceQuery to retrieve the token balances.

### Hedera network

mainnet, testnet

### Version

v2.17.5

### Operating system

macOS

**Comment by robkainz** [comment]
I'm trying to determine from the golang SDK release notes whether or not we can safely go back to v2.16.1 for our NFT release. 
* I do see that the PLATFORM_NOT_ACTIVE problem was fixed in 2.17.1 which we have seen from time to time in production, and I remember users sending us screenshots of that. It would be a shame not to have that fix.
* Looks like alias support may not be fully supported, which is probably ok for now for us.
* Regarding the "transactions now don't sign twice" fix, if we don't include this fix, will users be charged for the extra signature? Any other consequences?

Is there anything else we need to be aware of if we decide to revert to v2.16.1? Will all our staking and NFT-related functionality in our new release work flawlessly using the golang v2.16.1 Hedera SDK?

**Comment by andrix10** [comment]
I know hedera deprecated token balance from AccountBalanceQuery on their end, so even if you use v2.16.1 I think It would still be empty. Unless they still didn't go through with that.

**Comment by robkainz** [comment]
We are going to regression test with 2.16.1, and it is returning the token balances. Greg said the mainnet nodes would continue returning the token balance data until all mirrors properly support fetching unlimited token balances, and there would be a 6 month period once they start doing that before the mainnet nodes stop returning token balances as per HIP367. It’s just unfortunate that we cannot move to later Hedera golang SDKs until the mirrors are updated, but hopefully it won’t impact us too badly in the near future.

**Comment by andrix10** [comment]
That is a bit weird, they deprecated them in protobufs but they are still working? Didn't realize.

**Comment by ochikov** [comment]
@robkainz We've pushed a new release with v2.17.6. Can you test with the new one?

**Comment by robkainz** [comment]
Honestly it is too late now, regression testing is half done. We can include and test the latest library in our maintenance release when the time comes.

**Comment by Kalina-Todorova** [comment]
Hey @robkainz Sorry to hear that we didn't make it on time for your release. Let us know if all works as expected once you get to test out the latest release. I'm closing this ticket, but please feel free to reopen or file another one in case you face any further issues.
