### ISSUE TITLE
Add stats for transactions

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#611]
### Problem

There are times when transactions fail with `INVALID_NODE_ACCOUNT_ID`, `TRANSACTION_EXPIRED`, or other errors where transactions do not succeed. In order to debug these transaction failures the SDK needs to provide some stats.

### Solution

Log the transactions that were submitted in the last 30 minutes.

Stored locally and default is not enabled.

This should include:

- Transaction ID
- Node the transaction was submitted to
- Network response (either the network error or success response)
- The network is was submitted to (mainnet, testnet, previewnet)

**Comment by ochikov** [comment]
### Specifications and logger behaviour

- The default behaviour has to be ***OFF*** - no log statements if not explicitly set by the user
- The logger has to be able to be set on both client and transaction/query levels
    - If a logger is set for a specific transaction/query and the client also has a logger - we prioritize the one in the transaction/query
    - If a given transaction/query does not have a logger, we use the one from the client (if there is)

### Functionalities

- The logger api has to:
    - provide a way to change the level of the logger
    - provide a way to silence the logger (switch between on/off - meaning that if you switch it **off** and then turn it back ****on****, the level of the logger has to be the one before switching it to ******off****** in the first place
    - set/get methods for those fields
    - expose the logging methods of the library
        - currently the library used in JS SDK has the following log levels: *************trace, debug, info, warn, error, fatal*************

### Implementation **(*************suggestion from JS SDK**)***

- Create a *Logger* class which will basically encapsulate the logger library used in the SDK and expose necessary fields, methods, levels and so on
- Create a ********LogLevel******** class which will act as a mapping between the log levels from the library and levels in the SDK
- Create an example which will show the behaviour and all of the functionalities mentioned above

### What to log?

- Transaction ID
- Node Id and address of each transaction attempt
- When node is unhealthy
- Node the transaction was submitted to
- Network response (either the network error or success response)
- The network it was submitted to (mainnet, testnet, previewnet)
