### ISSUE TITLE
panic called in AddressBookQuery

### ISSUE THREAD

**Issue by ccherry-arculus** [hashgraph/hedera-sdk-go#625]
### Description

Perhaps some race condition - but at times when I am using a Client for some task the panic in AddressBookQuery fires and my program dies.

I have added a defer func to call recover and that does not help in this case.

Is the panic really required - can't the address book just get updated on the next interval?

### Steps to reproduce

The task I am doing is checking all the nodes to see if they are available by making an AccountBalanceQuery to each node.  Every 60 seconds I make the calls and for each call I create a new Client.

get the panic at address_book_query.go:145 +0x390

### Hedera network

mainnet

### Version

latest

### Operating system

macOS

**Comment by ccherry-arculus** [comment]
Appreciate the quick response...

**Comment by bamzedev** [comment]
Hey @ccherry-arculus, thanks for logging this issue. This should be fixed in v2.18.0, which will be released today.
