### ISSUE TITLE
logCtx should not be a global variable

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-sdk-go#627]
### Problem

We should not have a logger set as a global variable at initialization. Using the `init()` function in Go is generally frowned upon because there's no easy way to tell the order in which those get executed. Having a global variable with a logger makes testing difficult and causes strange side-effects when people embed the SDK inside their programs. [See Discord issue here.](https://discord.com/channels/373889138199494658/535491142280806400/1040277366527758376)
https://github.com/hashgraph/hedera-sdk-go/blob/develop/executable.go#L44

Structs that require a default logger should be able to set the logger via a method. Functions/methods that take a context, should be able to extract the logger from the `context.Context` to use.
https://github.com/rs/zerolog#pass-a-sub-logger-by-context

## Pass a logger by context

```golang
ctx := log.With().Str("component", "module").Logger().WithContext(ctx)

log.Ctx(ctx).Info().Msg("hello world")

// Output: {"component":"module","level":"info","message":"hello world"}
```

**Comment by ochikov** [comment]
Will be fixed together with https://github.com/hashgraph/hedera-sdk-go/issues/611
