### ISSUE TITLE
Running Example Questions

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#69]
1. I noticed when running the examples we use the os package to grab the OPERATOR_KEY and OPERATOR_ID. Does this mean the env variables have to be contained within the main.go file and cannot reference an .env file? If true, that would mean to run each example I would have to add the following to the main.go file along with any additional env variables I would need?

```
os.Setenv("OPERATOR_ID", "x.x.xxxx")
os.Setenv("OPERATOR_KEY", "302......")
```

If that is the case, can we prefer to follow the use of the dotenv package as in the other sdks?

2. I noticed that for each example we have a folder with the example name and within that folder we have the main.go file to run the example i.e. create_account/main.go. Are we able to simply name the main.go file to create_account.go and keep it within the examples folder as the other sdks and follow for each example?

**Comment by donaldthibeau** [comment]
1. Could you submit a PR with this incorporated?
2. Not possible in Go.

**Comment by rhysied** [comment]
Hi both,

In the demo application we [did](https://github.com/hashgraph/hello-hedera-audit-log-go), we use the `godotenv` module to load values from a config file. Just wanted to point it out as it may help with the first issue mentioned and avoid the need for you to have to update multiple `main.go` files if you were running several examples.

Cheers, Rhys.

**Comment by SimiHunjan** [comment]
Thanks for the reference @rhysied. Will post a PR this week.

**Comment by mehcode** [comment]
> If true, that would mean to run each example I would have to add the following to the main.go file along with any additional env variables I would need?

No. You would run like:

```
$env:OPERATOR_ID = "0.1.2"
$env:OPERATOR_KEY = "302...."

go run examples/ ...
```

assuming your using windows
