### ISSUE TITLE
Public key using examples/generate-keys.go is not changing with each invocation

### ISSUE THREAD

**Issue by tshear** [hashgraph/hedera-sdk-go#7]
1st iter: secret = 302e020100300506032b657004220420edafee84e6488940b07869906ffa97d432f67331a27aff3fc5cf71dfb2276110
public = 302a300506032b6570032100ef789a1a9e40bd45ff700a7f3a06cdb75c040efeaabcfdc0e8f92af0c55490f8
2nd iter: secret = 302e020100300506032b6570042204204cb6ce6f39f8814741a3fa0fdf606e618b0390818ddd27be6a7ff2cdedb5ff2a
public = 302a300506032b6570032100ef789a1a9e40bd45ff700a7f3a06cdb75c040efeaabcfdc0e8f92af0c55490f8

**Comment by mehcode** [comment]
Are you sure? 

```
 △ hashgraph/hedera-sdk/hedera-sdk-go go run examples/generate-keys.go                                                                                                       master :: 3m :: ⬢
secret = 302e020100300506032b65700422042007973990ec45960fc471ffeed363cd34b427cb5a3e8d09e02dcfce6c09fe3b37
public = 302a300506032b6570032100104538bacd328b54e1f0b59f0aedbeb591f5d433615f2370132b83bcd880e78e

 ▲ hashgraph/hedera-sdk/hedera-sdk-go go run examples/generate-keys.go                                                                                                      master :: 46s :: ⬢
secret = 302e020100300506032b657004220420b4f9d7036b5e51d0cebe8d4acaa43ec570032a75575e0229c845be1b8778ae59
public = 302a300506032b6570032100b471cefad1eaa24be2dff43233a4d9b3041faaca9c482172f9e93072e9a5d7d3
```

I just ran this locally and it seems fine.

**Comment by tshear** [comment]
Ryan:
  
 Yep. ran 5 more times both as go build and go run, same results.
  
 Here is info on machine:
  
 Microsoft Windows [Version 10.0.17134.407]
 Processor Intel Core i7-8550U CPU @ 1.80GHz 1.99 GHz  16.0GB memory
 Go: go version go1.11 windows/amd64
 gcc: gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
  
  
 Let me know if you need more. 

   
----------------------------------------
 DataparencyT  Timothy A. Shear, CEO
 Dataparency, LLC
 (248) 390-5566

  

----------------------------------------

**Comment by tshear** [comment]
Also
  
 cargo 1.29.0-nightly (2cd36b4ed 2018-07-25) if that matters.
  
   

   
----------------------------------------
 DataparencyT  Timothy A. Shear, CEO
 Dataparency, LLC
 (248) 390-5566

  

----------------------------------------

**Comment by mehcode** [comment]
It's possible it could be a bug in the windows environment. I'll try and take a look today.

**Comment by tshear** [comment]
Ryan:
  
 Debugging the code, the C routine in hedera.lib always returns the same buffer value even when the secret key changes. I see that the C code is doing dynamic memory. Does the lib use standard malloc calls? I remember couchbase having an issue using some type of special malloc call which Microsoft broke at some release. I'll see if I can find the issue post.
  
 Let me know what malloc call is being used in the  

 C.hedera_public_key_from_secret_key(&key.inner) 
 call. It might help me find the issue quicker.
   

   
----------------------------------------
 DataparencyT  Timothy A. Shear, CEO
 Dataparency, LLC
 (248) 390-5566

  

----------------------------------------

**Comment by mehcode** [comment]
I have verified this works as it should on Windows 10 in hedera-sdk-go v0.2.0. Can you please run `go get -u github.com/hashgraph/hedera-sdk-go` to make sure you're on the latest version.

**Comment by mehcode** [comment]
Seems like this is fixed. Re-open if you're still having problems.
