### ISSUE TITLE
Review Snyk report

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#750]
### Problem

There are some issues Synk has reported that need to be reviewed. 

### Solution

Review items found by Snyk.

**Comment by rokn** [comment]
I've reviewed the items from the Snyk report. Most of them are coming from various issues in go-ethereum or it's dependencies. We are on the latest version of go-ethereum and also we don't seem to be affected from those vulnerabilities in any way so I'll be closing this.
