### ISSUE TITLE
Client should not do blocking address book update during instantiation

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-go#759]
https://github.com/hashgraph/hedera-sdk-go/blob/f6a3c6f3720b45f6b077c156e5957db385dc539a/client.go#L142-L143

The blocking network address book update during client instantiation by `ClientForName`, `ClientForTestnet`, `ClientForPreviewnet`, `ClientForMainnet` may take quite some time to timeout in environments without internet access, thus blocks the application. We should move the initial address book update into the go routine.

A better option is add public functions like `func ClientForNameWithOptions(name string, options ClientOptions)` so users can choose to disable network address book update completely.

**Comment by rokn** [comment]
Hey, so we have a workaround for now for this, you can use the `ClientFromConfig` function to create a client without a mirror node:
```
client, err := ClientFromConfig([]byte(`{"network":"mainnet"}`)) // you use this for testnet/previewnet as well
```
and then you can set the mirror node again and start the update(if you want) which would start only the async one:
```
var mainnetMirror = []string{"mainnet-public.mirrornode.hedera.com:443"}
client.SetMirrorNetwork(mainnetMirror)
client.SetNetworkUpdatePeriod(updatePeriod) // default is 24 * time.Hour
```

We'll discuss further internally if we can make this process a bit easier.

**Comment by rokn** [comment]
Hey @xin-hedera, is the proposed solution above working for you, can we close this issue?

**Comment by rokn** [comment]
We have added this as a blocking call so that after client initialization the client is using a fresh copy of the address book. Otherwise we'd have to update the address book on every release.

**Comment by xin-hedera** [comment]
@rokn make sense even though I wish we had an extensible option in the API from the beginning... I'll use the workaround in rosetta.

With that, I agree we can close this ticket.
