### ISSUE TITLE
Occasional duplicate transaction id

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-go#78]
When running at high throughput, the network sometimes returns a duplicate transaction id.
Maybe a random number for the nanos would alleviate the problem and make it a lot less likely to occur.

**Comment by mehcode** [comment]
I would recommend to use a separate operator ID per thread to remove any potential for duplicate ID generation.

**Comment by mehcode** [comment]
Fixed in c2a1a2997ab624c2a3fcd53bb5f072976236e114
