### ISSUE TITLE
Potential bug in transaction.go

### ISSUE THREAD

**Issue by Coiling-Dragon** [hashgraph/hedera-sdk-go#793]
### Description

Running golangci-lint logs a potential issue in transaction.go:345:21 

```
	for i := 1; i < len(body); i++ {
		if reflect.TypeOf(body[0].Data) != reflect.TypeOf(body[i].Data) {
			return false, nil
		}
	}
	
transaction.go:345:21: G602: Potentially accessing slice out of bounds (gosec)
		if reflect.TypeOf(body[0].Data) != reflect.TypeOf(body[i].Data) {
		                  ^
```

### Steps to reproduce

golangci-lint run

### Hedera network

other

### Version

v2.24.2

### Operating system

None

**Comment by bamzedev** [comment]
https://github.com/hashgraph/hedera-sdk-go/pull/794 fixed this.
