### ISSUE TITLE
Discrepancy in Parameter Type for approveTokenAllowance Function Between JavaScript and Go SDKs

### ISSUE THREAD

**Issue by luciamunozdev** [hashgraph/hedera-sdk-go#814]
### Description

Description
I have encountered an inconsistency between the JavaScript SDK and the Go SDK when using the approveTokenAllowance function. In the [JavaScript SDK](https://github.com/hashgraph/hedera-sdk-js/blob/86a6cd608f35225b02e395c5110be54634cf1a44/src/account/AccountAllowanceApproveTransaction.js#L216), the spenderAccountId parameter can accept different types, including AccountId, ContractId, or a string representation. However, in the [Go SDK](https://github.com/hashgraph/hedera-sdk-go/blob/1a6ae161e3256472deb8f618a6dbe50a027bb5a8/account_allowance_approve_transaction.go#L154) , the spenderAccountId parameter is restricted to only accepting an AccountId.

JavaScript code:
```
   /**
     * @param {TokenId | string} tokenId
     * @param {AccountId | string} ownerAccountId
     * @param {AccountId | ContractId | string} spenderAccountId
     * @param {Long | number} amount
     * @returns {AccountAllowanceApproveTransaction}
     */
    approveTokenAllowance(tokenId, ownerAccountId, spenderAccountId, amount) {
    }
```

Go code:

```
// ApproveTokenAllowance
// Approve allowance of fungible token transfers for a spender.
func (transaction *AccountAllowanceApproveTransaction) ApproveTokenAllowance(tokenID TokenID, ownerAccountID AccountID, accountID AccountID, amount int64) *AccountAllowanceApproveTransaction {
	return transaction._ApproveTokenApproval(tokenID, &ownerAccountID, accountID, amount)
}
```

### Steps to reproduce

Go example when trying to run the function, to test it run the code
[index.go.txt](https://github.com/hashgraph/hedera-sdk-go/files/12805435/index.go.txt)

JavaScript example:
[index.js.txt](https://github.com/hashgraph/hedera-sdk-go/files/12805436/index.js.txt)

### Hedera network

testnet, previewnet

### Version

v2.30.0

### Operating system

macOS

**Comment by rokn** [comment]
Hey @luciamunozdev, as this is the same issue as in the [Java sdk](https://github.com/hashgraph/hedera-sdk-java/issues/1613). I'll be closing it as the case here is pretty much the same. If you have any more questions feel free to ping us or reopen the issue.
