### ISSUE TITLE
Can not install Hedera SDK go repo today, but it worked 5 days ago.

### ISSUE THREAD

**Issue by zydjohnHotmail** [hashgraph/hedera-sdk-go#817]
### Description

When trying to install the Hedera SDK for Go with the following command:

go install github.com/hashgraph/hedera-sdk-go/v2@latest
I receive the following error message:

package github.com/hashgraph/hedera-sdk-go/v2 is not a main package
This issue occurred on the following date:

2023-10-11
Steps to reproduce:

Create a new Go project.
Open a terminal window and navigate to the project directory.
Run the following command:
"
go install github.com/hashgraph/hedera-sdk-go/v2@latest
"

Expected behavior:

The Hedera SDK for Go should be installed successfully.

Actual behavior:

The following error message is displayed:

"
package github.com/hashgraph/hedera-sdk-go/v2 is not a main package
"

Environment:

Go version: 1.21.3
Operating system: Windows 10
Additional information:

This issue occurred on a project that was created 5 days ago and was previously working.

### Steps to reproduce

1. go install github.com/hashgraph/hedera-sdk-go/v2@latest
D:\GO\Hedera-Go>go install github.com/hashgraph/hedera-sdk-go/v2@latest
package github.com/hashgraph/hedera-sdk-go/v2 is not a main package

D:\GO\Hedera-Go>go version
go version go1.21.3 windows/amd64

D:\GO\Hedera-Go>

### Hedera network

testnet

### Version

latest version as of today.

### Operating system

Windows

**Comment by rokn** [comment]
Hey @zydjohnHotmail, can you try running 
```
go get github.com/hashgraph/hedera-sdk-go/v2
```

**Comment by zydjohnHotmail** [comment]
D:\GO\Hedera-Go>go get github.com/hashgraph/hedera-sdk-go/v2
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

D:\GO\Hedera-Go>dir
 Volume in drive D is SATABackup
 Volume Serial Number is 4425-E62C

 Directory of D:\GO\Hedera-Go

10/11/2023  09:10 PM    <DIR>          .
10/11/2023  09:10 PM    <DIR>          ..
10/11/2023  09:21 PM    <DIR>          .vs
10/11/2023  09:10 PM               981 main.go
               1 File(s)            981 bytes
               3 Dir(s)  324,448,563,200 bytes free

D:\GO\Hedera-Go>go install github.com/hashgraph/hedera-sdk-go/v2
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/hashgraph/hedera-sdk-go/v2@latest' to install the latest version

D:\GO\Hedera-Go>go install github.com/hashgraph/hedera-sdk-go/v2@latest
package github.com/hashgraph/hedera-sdk-go/v2 is not a main package

D:\GO\Hedera-Go>go version
go version go1.21.3 windows/amd64

D:\GO\Hedera-Go>
=> I think your go version could be old, otherwise you will see  the error I got.  Using old go version could work, but it is not a good idea, since you have to upgrade go version sooner or later, right?

**Comment by rokn** [comment]
Oh sorry for newer, go versions you need to run `go mod init <package_name>`(`go mod init test_package` for example) as go get has been deprecated for non modules. After that `go get github.com/hashgraph/hedera-sdk-go/v2` should work. Go install should be used to install commands and not libraries

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks, I followed your advice, and it works now.
But please change the readme, as it is misleading, for new go version, it will never work; and for more people to use this repo, old go version will be out of support, right?
