### ISSUE TITLE
Go SDK balance retrieval insists on operatorId being set, while JS sdk doesnt

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#83]
When fetching balance with Go SDK, it returns different balance from when fetched with JS/TS SDK.
**Go SDK**
```Go
client := hedera.ClientForTestnet()
accountId, err := hedera.AccountIDFromString("0.0.123352")
result, err := hedera.NewAccountBalanceQuery().SetAccountID(accountId).Execute(client)
fmt.Println(result) // returns incorrect balance 0
```

**JS/TS SDK**
```JS
const client = Client.forTestnet()`
console.log('current account balance:', 
  await new AccountBalanceQuery().setAccountId("0.0.123352").execute(client)); // returns correct balance 10 000
```

**Comment by gregscullard** [comment]
Hi, I've just tried to query the balance with the GoSDK for this same account and got `10000 ℏ`
Might be worth checking if an error was returned in `err`

**Comment by failfmi** [comment]
Why would be necessary in the Go SDK to set an Operator in the hedera.Client for a Balance Query?

**Comment by gregscullard** [comment]
Ok, I've updated the title of the issue, guess it's low priority now, but consistency would be good indeed.

**Comment by mehcode** [comment]
This looks to be a consistent issue in the Go SDK. 

Originally with Hedera, not having an operator meant your Client is useless. 

I'll ensure our SDK team knows about this one but I agree that its low priority. Note that I'm sure your operator doesn't actually need to be valid in any way. Use an operator of `0.0.0` with a key of all zeros. Could be a reasonable workaround for the time being.

**Comment by danielakhterov** [comment]
Stale issue; closing. Note: in version 2 the `OPERATOR_KEY` and `OPERATOR_ID` are no longer required environment variables.
