### ISSUE TITLE
Appending transaction body signatures to a transaction

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#84]
Is there currently a way in the SDK to append transaction body signatures to a transaction?
Scenario: send unsigned transaction & transaction body to a party, which will sign it and later append the signature to the transaction, so that it can be broadcasted?

**Comment by mehcode** [comment]
Please look to this example: https://github.com/hashgraph/hedera-sdk-go/blob/master/examples/multi_app_transfer/main.go

---

You can marshall the transaction to bytes, transfer through the network, unmarshall to a Transaction, and sign and execute.

**Comment by failfmi** [comment]
Problem is party signer does not know anything related to Hedera, calls `ed25519.Sign(privateKey, message)`.
