### ISSUE TITLE
Add Account Balance/Info, Contract Info Mirror Node Queries 

### ISSUE THREAD

**Issue by NicolaMirchev** [hashgraph/hedera-sdk-go#841]
### Problem

Detailed: https://github.com/hashgraph/hedera-sdk-reference/issues/144

### Solution

Add a service to query balance data for the corresponding network:

Detailed:
https://www.notion.so/limechain/Mirror-Node-Queries-fe0d563db0d545fdafd7a0a5137fe5bd

HIP: https://hips.hedera.com/hip/hip-873

Mirror Node: https://github.com/hashgraph/hedera-mirror-node/issues/7386

**Comment by agadzhalov** [comment]
Work is continued on separated issues

Go-TCK[: Implement JSON-RPC methods for ](https://github.com/hashgraph/hedera-sdk-go/issues/874)AccountCreateTransaction
Go-TCK: [Implement JSON-RPC methods for](https://github.com/hashgraph/hedera-sdk-go/issues/875) AccountUpdateTransaction
Go-TCK[: Implement JSON-RPC methods for ](https://github.com/hashgraph/hedera-sdk-go/issues/876)AccountDeleteTransaction
Go-TCK[: Implement JSON-RPC methods for ](https://github.com/hashgraph/hedera-sdk-go/issues/877)AccountInfoQuery
