### ISSUE TITLE
Accessing Transaction Body

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#85]
Is there a way in the SDK to get the transaction body, so that I can get its transaction data?
I am asking that with the idea of rebuilding an object with which I have made the actual transaction in first place.

Example:
```JSON
{"type": "CRYPTOTRANSFER", "account": {"address": "0.0.123352"}, "amount": "-100"},
{"type": "CRYPTOTRANSFER", "account": {"address": "0.0.123518"}, "amount": "+100"}
```
to
```Go
hedera.NewCryptoTransferTransaction()
.AddSender(sender, senderAmount)
.AddRecipient(recipient, recipientAmount)
```

**Comment by gregscullard** [comment]
@failfmi could you elaborate further ? Are you trying (for example) to create an instance of a CryptoTransferTransaction object from an existing byte array payload so that you can further modify the transaction ?

**Comment by gregscullard** [comment]
This example may be useful, it shows how an existing transaction can be marshalled and un-marshalled, maybe achieving what you're hoping to achieve ?

https://github.com/hashgraph/hedera-sdk-go/blob/master/examples/multi_app_transfer/main.go

**Comment by failfmi** [comment]
The example I've provided (the json) based on type I build different types of transactions (if type is `CRYPTOCREATEACCOUNT`, I will have to do
```go
hedera.NewAccountCreateTransaction()
```
My question is it possible somehow to do the other way around - from the `hedera.Transaction` to generate the json. (accessing `transaction.pb`, its bodyData, etc.)

**Comment by gregscullard** [comment]
Clarifying the requirement here, once transaction bytes have been unmarshalled to a Transaction object, it should be possible to inspect its properties (and the properties of its constituent parts) via getters allowing a third party counter signer to review the contents of the transaction they are about to sign.

**Comment by danielakhterov** [comment]
Stale issue, and mentioned PR is closed, so closing this issue as well. If you're having further issues please re-open.
