### ISSUE TITLE
Add new JSON-RPC methods for `Account` to TCK server 

### ISSUE THREAD

**Issue by NicolaMirchev** [hashgraph/hedera-sdk-go#860]
### Problem

Currently we have only `setup` and `reset` methods, which are configuring the sdk client object.

We want to start implementing the composition with the TCK driver, which means that we should fill the function mapping on the server side (Go TCK server).
For now we can implement all methods, which are used from the [TCK driver](https://github.com/hashgraph/hedera-sdk-tck/tree/main) at commit `26c23fa` and test the execution flow.

The following process will give us a template on how we should continue implementing each TCK spec and build simple structure inside the Go SDK project regarding tck stuff. 

### Solution

__Add the following methods:__

Account:
- createAccount
- createAccountFromAlias
- updateAccountMemo
- updateAccountKey
- getAccountInfo
- deleteAccount

Key:
- generatePublicKey
- generatePrivateKey

### Note:
- "createAccount": 
    - `should set account auto renew period to 2,592,000 seconds`
    - `Max token set to the maximum`

- "createAccountFromAlias"
    - `Create account with alias`

- "updateAccountKey"
    - `Creates an account and sets staked account ID with no input`
 
- "updateAccountMemo"
    - `should test memo field is too long`

**Comment by agadzhalov** [comment]
Work will be continued on those issues #874  #875  #876 #877 and this [PR feat(Go-TCK): Implement JSON-RPC methods for AccountCreateTransaction, AccountUpdateTransaction, AccountDeleteTransaction and AccountInfoQuery ](https://github.com/hashgraph/hedera-sdk-go/pull/879)
