### ISSUE TITLE
[To investigate] Is transaction with property in Hbars serialised correctly

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-sdk-go#873]
### Problem

Serializing and deserializing a transaction with an Hbar property gives an incorrect property value in JS SDK.
In the example below you may see that the initial balance is 3 Hbars. After deserializing the initial balance becomes 300000000 hbars

```
const { AccountCreateTransaction, Hbar, HbarUnit } = require('@hashgraph/sdk');

const transaction = new AccountCreateTransaction().setInitialBalance(
  Hbar.fromString('3', HbarUnit.Hbar)
);
console.log(transaction.initialBalance.toString(HbarUnit.Hbar)); // 3 ℏ
const transactionBytes = transaction.toBytes();

const transactionFromBytes =
  AccountCreateTransaction.fromBytes(transactionBytes);
console.log(transactionFromBytes.initialBalance.toString(HbarUnit.Hbar)); // 300000000 ℏ
```

### Solution

Let's double check if this is reproducible in Go SDK as well. If it's not a problem in the SDK close the task directly.

**Comment by gsstoykov** [comment]
![image](https://github.com/hashgraph/hedera-sdk-go/assets/146725010/70fd45ee-72c5-48d0-a420-71aa15f85aad)
Results can also be seen in pipeline.
