### ISSUE TITLE
client.replaceNodes / setNetwork doesn't replace all nodes

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-go#89]
Using client.replaceNodes, does not replace all nodes, it replaces nodes it can find, or adds to the list of nodes.

I created a client with .forPreviewNet, then .replaceNodes with a single node as input, the client's list of nodes still contained four nodes.

It looks as though the `replaceNodes` / `setNetwork` (in v2) is missing a re-initialisation of the array of nodes, thus not really replacing nodes.

This can be overcome by creating the client with `NewClient` in the first place, however the methods `replaceNodes` / `setNetwork` are misleading.

**Comment by danielakhterov** [comment]
I don't know when, but I believe this issue is fixed on master. Just added a test https://github.com/hashgraph/hedera-sdk-go/blob/master/client_test.go#L52 which passes.
