### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-go#91]
(raised here, equally applicable to JS/Java SDKs)

Additional examples should be provided to illustrate:
* Loading a list of nodes from JSON
* Loading a list of node from a file
* Illustrate best practice in error handling when executing a transaction (all current examples expect sunny day scenarios)
* Illustrate best practice in error handling when executing a query (all current examples expect sunny day scenarios)

**Comment by danielakhterov** [comment]
This is a very fair point. For your first two points I agree with should have some examples for. However, what would you consider we should do on rainy days? I'm thinking the best we can do is just log an issue. From my understanding there is not much a user can do when a transaction fails besides changing the code itself.

**Comment by danielakhterov** [comment]
We've added  some examples here: https://github.com/hashgraph/hedera-sdk-go/blob/master/examples/client_from_file
